
title: Vologue's Blog
# email: raghav.sp98@gmail.com
description: ""
baseurl: "" 
url: "https://blog.vologue.dev" 
twitter_username: _vologue
github_username:  vologue

show_excerpts: false
# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
minima:
  skin: dark
  social_links:
    twitter: _vologue
    github: vologue
author:
  name: vologue
  email: "raghav.sp98@gmail.com"
