name: Build & deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
        allow-failures: [false]
        include:
          - ruby: head
    steps:
      # - uses: ruby/setup-ruby@v1.9.0
      #   with:
      #     ruby-version: ${{ matrix.ruby-version }}
          # bundler-cache: true
      - run: gem install bundle 
      - uses: actions/checkout@v2
      - run: bundle install
      - run: bundle exec jekyll build
      - run: ls
