name: Build & deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
        allow-failures: [false]
        include:
          - ruby: head
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: |
          # bundle install
          # bundle exec jekyll build
          ls
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region: ap-south-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-session-name: deploy-blog
      - run: |
          aws sts get-caller-identity 
          aws s3 cp --acl public-read _site/. s3://blog.vologue.dev/ --recursive --cache-control 0