name: Build & deploy
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
        allow-failures: [false]
        include:
          - ruby: head
    steps:
      - uses: actions/checkout@master
      - name: Build
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
        run: |
          bundle install
          bundle exec jekyll build
          ls
