name: Build & deploy
on: [push]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ['3.0']
        allow-failures: [false]
        include:
          - ruby: head
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '3.0'
      - run: |
          # bundle install
          # bundle exec jekyll build
          ls
      - id: install-aws-cli
        uses: unfor19/install-aws-cli-action@master
        with:
          version: "2"
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      - run: |
          aws sts get-caller-identity 
          # aws s3 cp --acl public-read _site/. s3://blog.vologue.dev/ --recursive --cache-control 0